pip install tensorflow

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [6]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [7]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [8]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='str')

In [9]:
x=df[['soil_moisture','temperature_c','sunlight_hours']]
y=df['needs_water']

In [11]:
x_min=x.min()
x_max=x.max()
x_scaled=(x-x_min)/(x_max-x_min+1e-8)

In [12]:
x_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.25,random_state=42,stratify=y)

In [16]:
model=keras.Sequential([
    layers.Input(shape=(x_train.shape[1],)),  #Input layer
    layers.Dense(8,activation='relu'),     #hidden layer
    layers.Dense(1,activation='sigmoid')   #output layer
])

In [18]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])
#sgd is Stochastic Gradient Descent-->It decides how the model will update its weights to improve its predictions.
#Loss tells us how wrong the model's prediction is. binary_crossentropy is used when you have 2 classes.
#

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [23]:
history=model.fit(
    x_train.values,y_train.values,
    validation_data=(x_test.values,y_test.values),
    epochs=100,batch_size=4,verbose=1
)
#This controls what Keras prints while training. 1 means you'll see a progress bar and training information
#the training results are stored in history
#batch size= number of samples processed before updating the model's weights.
#Instead of giving the model the entire training dataset at once, it processes 4 samples at a time.

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.9167 - loss: 0.6057 - val_accuracy: 1.0000 - val_loss: 0.6289
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.9167 - loss: 0.6051 - val_accuracy: 1.0000 - val_loss: 0.6283
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9167 - loss: 0.6042 - val_accuracy: 1.0000 - val_loss: 0.6278
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.6042 - val_accuracy: 1.0000 - val_loss: 0.6273
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.6039 - val_accuracy: 1.0000 - val_loss: 0.6267
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9167 - loss: 0.6034 - val_accuracy: 1.0000 - val_loss: 0.6262
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.9167 - loss: 0.6029 - val_accuracy: 1.0000 - val_loss: 0.6257
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.9167 - loss: 0.6021 - val_accuracy: 1.0000 - val_loss: 0.6251
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9167 - loss: 0.6040 - val_accuracy: 1.0000 - val_loss: 0.6246
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9167 - loss: 0.6014 - val_accuracy: 1.0000 - val_loss: 0.6240
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9167 - loss: 0.6002 - val_accuracy: 1.0000 - val_loss: 0.6235
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9167 - loss: 0.6001 - val_accuracy: 1.0000 - val_loss: 0.6229
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9167 - loss: 0.6021 - val_accuracy: 1.0000 - val_loss: 0.6224
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9167 - loss: 0.5984 - val_accuracy: 1.0000 - val_loss: 0.6218
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.9167 - loss: 0.6004 - val_accuracy: 1.0000 - val_loss: 0.6213
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5975 - val_accuracy: 1.0000 - val_loss: 0.6207
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.5976 - val_accuracy: 1.0000 - val_loss: 0.6202
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9167 - loss: 0.5968 - val_accuracy: 1.0000 - val_loss: 0.6197
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9167 - loss: 0.5966 - val_accuracy: 1.0000 - val_loss: 0.6191
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9167 - loss: 0.5953 - val_accuracy: 1.0000 - val_loss: 0.6186
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9167 - loss: 0.5953 - val_accuracy: 1.0000 - val_loss: 0.6180
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.9167 - loss: 0.5948 - val_accuracy: 1.0000 - val_loss: 0.6175
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.9167 - loss: 0.5942 - val_accuracy: 1.0000 - val_loss: 0.6169
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9167 - loss: 0.5932 - val_accuracy: 1.0000 - val_loss: 0.6164
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9167 - loss: 0.5938 - val_accuracy: 1.0000 - val_loss: 0.6158
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9167 - loss: 0.5921 - val_accuracy: 1.0000 - val_loss: 0.6153
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.9167 - loss: 0.5942 - val_accuracy: 1.0000 - val_loss: 0.6147
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.9167 - loss: 0.5941 - val_accuracy: 1.0000 - val_loss: 0.6142
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5914 - val_accuracy: 1.0000 - val_loss: 0.6136
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9167 - loss: 0.5901 - val_accuracy: 1.0000 - val_loss: 0.6131
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9167 - loss: 0.5900 - val_accuracy: 1.0000 - val_loss: 0.6125
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9167 - loss: 0.5889 - val_accuracy: 1.0000 - val_loss: 0.6120
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5888 - val_accuracy: 1.0000 - val_loss: 0.6114
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.9167 - loss: 0.5879 - val_accuracy: 1.0000 - val_loss: 0.6109
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9167 - loss: 0.5883 - val_accuracy: 1.0000 - val_loss: 0.6103
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5872 - val_accuracy: 1.0000 - val_loss: 0.6097
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9167 - loss: 0.5867 - val_accuracy: 1.0000 - val_loss: 0.6092
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9167 - loss: 0.5868 - val_accuracy: 1.0000 - val_loss: 0.6086
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9167 - loss: 0.5852 - val_accuracy: 1.0000 - val_loss: 0.6081
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.5867 - val_accuracy: 1.0000 - val_loss: 0.6075
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.5846 - val_accuracy: 1.0000 - val_loss: 0.6070
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9167 - loss: 0.5842 - val_accuracy: 1.0000 - val_loss: 0.6065
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.5835 - val_accuracy: 1.0000 - val_loss: 0.6059
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.9167 - loss: 0.5832 - val_accuracy: 1.0000 - val_loss: 0.6053
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9167 - loss: 0.5818 - val_accuracy: 1.0000 - val_loss: 0.6048
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9167 - loss: 0.5813 - val_accuracy: 1.0000 - val_loss: 0.6042
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.9167 - loss: 0.5810 - val_accuracy: 1.0000 - val_loss: 0.6037
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.9167 - loss: 0.5810 - val_accuracy: 1.0000 - val_loss: 0.6031
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.5797 - val_accuracy: 1.0000 - val_loss: 0.6025
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.5794 - val_accuracy: 1.0000 - val_loss: 0.6020
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.9167 - loss: 0.5788 - val_accuracy: 1.0000 - val_loss: 0.6014
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.9167 - loss: 0.5783 - val_accuracy: 1.0000 - val_loss: 0.6008
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9167 - loss: 0.5783 - val_accuracy: 1.0000 - val_loss: 0.6003
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.9167 - loss: 0.5769 - val_accuracy: 1.0000 - val_loss: 0.5997
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.9167 - loss: 0.5769 - val_accuracy: 1.0000 - val_loss: 0.5991
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9167 - loss: 0.5765 - val_accuracy: 1.0000 - val_loss: 0.5986
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9167 - loss: 0.5751 - val_accuracy: 1.0000 - val_loss: 0.5980
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9167 - loss: 0.5750 - val_accuracy: 1.0000 - val_loss: 0.5974
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9167 - loss: 0.5742 - val_accuracy: 1.0000 - val_loss: 0.5968
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9167 - loss: 0.5743 - val_accuracy: 1.0000 - val_loss: 0.5963
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9167 - loss: 0.5750 - val_accuracy: 1.0000 - val_loss: 0.5957
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.9167 - loss: 0.5744 - val_accuracy: 1.0000 - val_loss: 0.5951
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9167 - loss: 0.5717 - val_accuracy: 1.0000 - val_loss: 0.5945
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.9167 - loss: 0.5721 - val_accuracy: 1.0000 - val_loss: 0.5939
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.9167 - loss: 0.5707 - val_accuracy: 1.0000 - val_loss: 0.5933
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9167 - loss: 0.5705 - val_accuracy: 1.0000 - val_loss: 0.5928
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9167 - loss: 0.5705 - val_accuracy: 1.0000 - val_loss: 0.5922
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.9167 - loss: 0.5719 - val_accuracy: 1.0000 - val_loss: 0.5916
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9167 - loss: 0.5690 - val_accuracy: 1.0000 - val_loss: 0.5910
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9167 - loss: 0.5697 - val_accuracy: 1.0000 - val_loss: 0.5904
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.9167 - loss: 0.5673 - val_accuracy: 1.0000 - val_loss: 0.5898
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.5672 - val_accuracy: 1.0000 - val_loss: 0.5892
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.9167 - loss: 0.5660 - val_accuracy: 1.0000 - val_loss: 0.5886
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9167 - loss: 0.5666 - val_accuracy: 1.0000 - val_loss: 0.5881
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9167 - loss: 0.5648 - val_accuracy: 1.0000 - val_loss: 0.5875
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.9167 - loss: 0.5648 - val_accuracy: 1.0000 - val_loss: 0.5868
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9167 - loss: 0.5638 - val_accuracy: 1.0000 - val_loss: 0.5862
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.9167 - loss: 0.5643 - val_accuracy: 1.0000 - val_loss: 0.5857
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.5638 - val_accuracy: 1.0000 - val_loss: 0.5851
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9167 - loss: 0.5630 - val_accuracy: 1.0000 - val_loss: 0.5845
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9167 - loss: 0.5614 - val_accuracy: 1.0000 - val_loss: 0.5839
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9167 - loss: 0.5616 - val_accuracy: 1.0000 - val_loss: 0.5833
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.9167 - loss: 0.5622 - val_accuracy: 1.0000 - val_loss: 0.5827
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.5625 - val_accuracy: 1.0000 - val_loss: 0.5821
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9167 - loss: 0.5599 - val_accuracy: 1.0000 - val_loss: 0.5815
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9167 - loss: 0.5584 - val_accuracy: 1.0000 - val_loss: 0.5809
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9167 - loss: 0.5592 - val_accuracy: 1.0000 - val_loss: 0.5803
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.9167 - loss: 0.5595 - val_accuracy: 1.0000 - val_loss: 0.5796
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9167 - loss: 0.5571 - val_accuracy: 1.0000 - val_loss: 0.5790
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9167 - loss: 0.5560 - val_accuracy: 1.0000 - val_loss: 0.5784
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9167 - loss: 0.5556 - val_accuracy: 1.0000 - val_loss: 0.5778
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9167 - loss: 0.5553 - val_accuracy: 1.0000 - val_loss: 0.5772
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9167 - loss: 0.5544 - val_accuracy: 1.0000 - val_loss: 0.5766
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.9167 - loss: 0.5561 - val_accuracy: 1.0000 - val_loss: 0.5760
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9167 - loss: 0.5532 - val_accuracy: 1.0000 - val_loss: 0.5754
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9167 - loss: 0.5533 - val_accuracy: 1.0000 - val_loss: 0.5748
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9167 - loss: 0.5524 - val_accuracy: 1.0000 - val_loss: 0.5742
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.9167 - loss: 0.5542 - val_accuracy: 1.0000 - val_loss: 0.5736
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9167 - loss: 0.5519 - val_accuracy: 1.0000 - val_loss: 0.5730
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9167 - loss: 0.5507 - val_accuracy: 1.0000 - val_loss: 0.5724